FROM ubuntu

LABEL Mainainer=jonathan.zhou@berkeley.edu \
      Description="Container for saving face pics to S3 bucket"

WORKDIR /

# Setup of drivers
RUN apt-get update
RUN apt-get install -y software-properties-common
RUN apt-get update && apt-get install -y \
    curl \
    git \
    python3.6 \
    python3-pip \
    python-opencv \
    python3-opencv \
    mosquitto \
    mosquitto-clients \
    vim \
    iputils-ping \
    libhdf5-dev \
    python3-numpy \
    python3-setuptools \
    python3-h5py \
    python3-wheel
RUN apt-get clean

RUN pip3 install paho-mqtt
RUN pip3 install opencv-python

COPY saver.py
CMD python3 saver.py
